listen_addresses: "0.0.0.0:3000"
web_ui: enable-for-all

postgres:
  connection_string: ${DATABASE_URL}

  auto_publish:
    from_schemas:
      - landslide_v2

    tables: false

    functions:
      from_schemas:
        - landslide_v2
      source_id_format: '{schema}.{function}'

